from __future__ import annotations

import hashlib
from pathlib import Path

from artist_portrait_editor.config_loader import load_project_config
from artist_portrait_editor.constants import DATA_DIR, RUNS_DIR, WORKSPACE_DIR
from artist_portrait_editor.models.source import SourceRecord
from artist_portrait_editor.models.state import ActiveMode, OverallStatus, StepLedgerEntry, StepStatus
from artist_portrait_editor.models.style_template import AestheticStyle, ContentFormTemplate, CreativeCombinationExample, CreativeTechnique, EmotionalArc, StyleTemplatePackage, TemplateCompatibility
from artist_portrait_editor.run_records import environment_snapshot, new_run_id, utc_now, write_json
from artist_portrait_editor.workspace_state import atomic_write_text, fingerprint_file, fingerprint_inputs, load_state, project_root, save_state, write_run_report


class StyleTemplatesError(RuntimeError): pass
def _beat(beat, low, high, purpose): return {"beat": beat, "minimum_ratio": low, "maximum_ratio": high, "purpose": purpose}
def _content(template_id, name, family, types, keywords, shots, rhythm, audio, bgm, text="restrained"):
    return ContentFormTemplate(template_id=template_id,name=name,form_family=family,intended_source_types=types,brief_keywords=keywords,intended_platforms=["douyin","bilibili","xiaohongshu"],intended_aspects=["16:9","9:16"],structure=[_beat("hook",.05,.18,"establish a motivated opening"),_beat("context",.08,.28,"ground person, role, place, or premise"),_beat("build",.42,.72,"develop evidence and variation"),_beat("payoff",.10,.28,"land an earned ending or deliberate non-closure")],shot_duration_range_seconds=shots,rhythm_policy=rhythm,source_audio_policy=audio,bgm_policy=bgm,subtitle_density=text,maximum_characters_per_second=8 if text=="dense" else 6.5,transition_policy="cuts are default; bends or breaks require form/feeling/meaning/risk explanation",composition_policy="protect subject, action, context, and text-safe regions according to the selected form",required_evidence=["source provenance","exact ranges","semantic or manual review for meaning claims"],acceptance_checks=["opening is intentional","structure supports the person","rhythm is not mechanical","sound hierarchy is clear","text is readable","ending or non-ending is deliberate"],hard_incompatibilities=["no evidence supports the stated subject or form"])

CONTENT_TEMPLATES=[
 _content("stage_performance_portrait","Stage Performance Portrait","performance",["stage_performance","live_performance"],["stage","performance","舞台","演出"],(1.5,8),"follow gesture/phrase evidence; complete breathing may override cut density","performance source audio is primary","avoid unrelated BGM over a performance mix","minimal"),
 _content("interview_portrait","Interview Portrait","spoken",["interview"],["interview","采访","访谈"],(3,14),"thought and sentence boundaries dominate","speech is primary","sparse ducked instrumental only after voice review","moderate"),
 _content("event_montage","Event Montage","event",["public_event","variety_show"],["event","festival","活动","盛典"],(.8,5),"vary action, scale, source, and ambience","retain useful sync and ambience","one selected track may organize montage","restrained"),
 _content("short_talking_head","Short Talking Head","spoken",["interview","other"],["talk","口播","观点"],(1.5,8),"tight speech pacing with intentional pauses","voice is primary","optional aggressively ducked BGM","dense"),
 _content("promotional_short","Promotional Short","promotional",["public_event","behind_the_scenes","fan_edit","other"],["promo","宣传","发布"],(1,5),"controlled escalation and information peaks","explicit dialogue/ambience/music hierarchy","phrase-aware explicit BGM selection","restrained"),
 _content("documentary_portrait","Documentary Portrait","documentary",["interview","public_event","behind_the_scenes","rehearsal"],["documentary","纪实","人物"],(2.5,15),"meaning, observation, and environmental texture dominate","speech and location sound are evidence","sparse music or silence; never manufacture emotion","restrained"),
 _content("film_role_montage","Film Role Montage","fiction",["film_scene"],["film","电影","角色"],(1.5,8),"role/action/dialogue relations shape nonlinear montage","distinguish role dialogue from real-person speech","score may bridge roles only with semantic review","minimal"),
 _content("television_role_arc","Television Role Arc","fiction",["tv_scene"],["television","电视剧","剧集","角色"],(2,10),"compress a role arc without inventing causality","preserve dialogue ownership and scene context","motif-led score must not erase dialogue","restrained"),
 _content("music_video_portrait","Music Video Portrait","performance",["music_video"],["music video","mv","音乐录像"],(.7,6),"visual motifs may lead while lyrics remain separate evidence","music mix is structural, not automatically clean BGM","reuse source song unless explicitly replacing","minimal"),
 _content("musical_theatre_portrait","Musical Theatre Portrait","performance",["musical_scene"],["musical","音乐剧"],(2,12),"song, acting, blocking, and breath stay connected","do not split lyric, role, and performer identity","source performance music is primary","minimal"),
 _content("theatre_performance_portrait","Theatre Performance Portrait","performance",["theatre_scene"],["theatre","话剧","戏剧"],(3,18),"longer dramatic beats may intentionally resist cutting","dialogue and stage space are primary","music is sparse unless part of performance","minimal"),
 _content("variety_persona","Variety Persona","event",["variety_show"],["variety","综艺"],(1.5,8),"reaction, interaction, and persona evidence must remain contextual","preserve speaker/reaction ownership","light BGM must not distort dialogue","moderate"),
 _content("rehearsal_process","Rehearsal Process","process",["rehearsal"],["rehearsal","排练"],(2,15),"process, repetition, failure, and improvement may form the arc","retain instruction, effort, and room sound","music cannot erase process evidence","restrained"),
 _content("behind_scenes_portrait","Behind-The-Scenes Portrait","process",["behind_the_scenes"],["behind","幕后","花絮"],(1.5,12),"contrast public image with labor and private texture","retain candid speech and environment","BGM should support, not polish away reality","restrained"),
 _content("cross_media_portrait","Cross-Media Portrait","cross_media",["interview","stage_performance","film_scene","tv_scene","rehearsal","behind_the_scenes","public_event"],["cross-media","跨媒介","不同舞台"],(1,12),"relationships across media create meaning; chronology is optional","distinguish real person, role, lyric, and commentary","sound bridges may connect media with explicit provenance","restrained"),
 _content("fan_creation_montage","Fan-Creation Montage","fan_creation",["fan_edit","film_scene","tv_scene","stage_performance"],["fan edit","混剪","二创"],(.6,6),"motif, contrast, repetition, and transformation may lead","preserve borrowed audio identity and contamination risk","explicitly selected music may drive structure","minimal"),
]

def _style(style_id,name,palette,pacing,image,color,bgm,text,transition,risks):
 return AestheticStyle(style_id=style_id,name=name,emotional_palette=palette,pacing_character=pacing,image_character=image,color_direction=color,bgm_character=bgm,text_character=text,transition_character=transition,suitable_intents=palette,failure_risks=risks,evidence_requirements=["project intent","playback review","semantic evidence for emotion claims"])
AESTHETIC_STYLES=[
 _style("idol_gloss","Idol Gloss",["admiration","radiance"],"precise peaks with protected beauty shots","performer-forward polish","clean luminous contrast","bright rhythmic or elegant pop","minimal elegant emphasis","clean cuts and motivated flashes",["empty worship","over-polish"]),
 _style("hot_blooded","Hot-Blooded",["drive","release"],"accelerating pressure and explosive payoff","kinetic action and impact","high contrast energetic","driving percussion or rock/electronic energy","short forceful text","hard cuts, rupture, speed variation",["false climax","fatigue"]),
 _style("inspirational","Inspirational",["struggle","growth","hope"],"setback-to-rise progression","effort, process, achievement","warm lift from restrained start","progressive score with earned lift","clear restrained statements","build-oriented transitions",["manufactured struggle","cliche uplift"]),
 _style("restrained_premium","Restrained Premium",["distance","control","aftertaste"],"sparse cuts and intentional duration","clean composition and negative space","controlled neutral palette","minimal texture or silence","very sparse typography","strict cuts, fades, intentional stillness",["coldness","empty slowness"]),
 _style("cinematic","Cinematic",["tension","scale","immersion"],"variable dramatic pacing","depth, motifs, visual continuity","filmic contrast tied to source","thematic score and sound design","title-led, low density","motivated match/sound bridges",["trailer imitation","overstatement"]),
 _style("healing","Healing",["gentleness","safety","renewal"],"breathing pace with soft progression","human details and environment","soft natural warmth","light acoustic/ambient","quiet readable text","gentle cuts and dissolves",["sentimentality","lack of direction"]),
 _style("romantic","Romantic",["attraction","intimacy","longing"],"lingering details and rhythmic recurrence","looks, gestures, visual rhyme","soft or rich warmth","melodic motif","poetic sparse text","match cuts and delayed completion",["invented relationship","sugar coating"]),
 _style("melancholic","Melancholic",["loss","distance","memory"],"held pauses and delayed release","absence, fragments, negative space","desaturated or cool restraint","sparse minor/ambient texture","fragmented minimal text","ellipses, silence, unresolved cuts",["manufactured sadness","monotony"]),
 _style("dreamy","Dreamy",["wonder","drift","ambiguity"],"floating rhythm with selective rupture","soft focus, repetition, surreal relation","pastel or luminous haze when source permits","ambient/electronic drift","light poetic fragments","dissolves, loops, temporal slips",["meaningless decoration","loss of subject"]),
 _style("epic","Epic",["scale","destiny","triumph"],"large dynamic arcs","wide scale and decisive close-ups","deep contrast and scale","orchestral/hybrid only with earned structure","declarative sparse text","large motivated transitions",["inflated stakes","generic trailer"]),
 _style("nostalgic","Nostalgic",["memory","time","affection"],"recollection rhythm and temporal echoes","texture, repetition, archival relation","source-respectful faded warmth","period-aware or memory-like music","dates/quotes only with evidence","echoes and associative cuts",["fake history","filter dependence"]),
 _style("documentary_raw","Documentary Raw",["truth","labor","presence"],"observational and evidence-led","imperfection and environment remain","minimal correction","location sound first","factual restrained text","motivated cuts only",["confusing rawness with honesty","privacy loss"]),
 _style("experimental_contrast","Experimental Contrast",["friction","surprise","reinterpretation"],"deliberate discontinuity","collision, repetition, mismatch","contrast may change by section","sound/image dislocation allowed","text may counterpoint image","rupture and nonlinearity",["randomness","unreadable intent"]),
 _style("absurdist_play","Absurdist Play",["humor","estrangement","release"],"anti-rhythm and sharp timing","unexpected relation and deadpan hold","source-led with selective exaggeration","ironic or sparse sound","timed concise text","smash cuts and intentional mismatch",["mocking subject","random meme logic"]),
]

def _tech(i,n,mode,form,feeling,meaning,risk,verify,fallback): return CreativeTechnique(technique_id=i,name=n,default_rule_mode=mode,form=form,expected_feeling=feeling,meaning_requirement=meaning,principal_risk=risk,playback_verification=verify,fallback=fallback)
CREATIVE_TECHNIQUES=[
 _tech("chronological_continuity","Chronological Continuity","follow","preserve source order","clarity","time progression matters","predictability","continuity remains intelligible","shorten without reordering"),
 _tech("nonlinear_reorder","Nonlinear Reorder","bend","reorder evidence-backed ranges","curiosity","new order reveals theme","false causality","meaning survives without invented events","restore chronology"),
 _tech("delayed_payoff","Delayed Payoff","bend","withhold completion or climax","anticipation","delay serves person/theme","frustration","payoff feels earned","move payoff earlier"),
 _tech("extreme_reversal","Extreme Reversal","break","switch style, sound, rhythm, or meaning frame sharply","shock and reinterpretation","before/after relation has evidence","gimmick or false meaning","viewers can explain what changed and why","use a subtle reversal"),
 _tech("sound_image_dislocation","Sound/Image Dislocation","break","separate sound time or meaning from image","friction or memory","counterpoint is traceable","misattribution","audio ownership remains clear","restore sync sound"),
 _tech("intentional_silence","Intentional Silence","bend","remove or hold sound around a decision","attention and vulnerability","silence reveals a real moment","empty pause","pause increases focus in playback","retain low ambience"),
 _tech("long_take_breathing","Long-Take Breathing","break","intentionally refuse expected cuts","presence and tension","performance needs full breath","drag","held duration remains compelling","trim to verified action"),
 _tech("contrast_montage","Contrast Montage","bend","juxtapose opposing media, roles, or states","discovery","contrast is evidence-backed","false equivalence","contrast clarifies person/theme","separate contexts"),
 _tech("motif_repetition","Motif Repetition","bend","repeat image, phrase, gesture, or sound","memory and emphasis","motif recurs in source","redundancy","repetition accumulates meaning","use motif once"),
 _tech("intentional_rupture","Intentional Rupture","break","break established pacing/composition/style","disorientation then attention","rupture marks a real turn","randomness","turn is legible and consequential","use a conventional transition"),
]

def _arc(i,n,phases,strength,req,fail): return EmotionalArc(arc_id=i,name=n,phases=phases,reversal_strength=strength,evidence_requirement=req,failure_mode=fail)
EMOTIONAL_ARCS=[
 _arc("linear_rise","Linear Rise",["setup","build","release"],"none","evidence supports increasing intensity","flat escalation"),
 _arc("quiet_late_release","Quiet Late Release",["restraint","accumulation","late release"],"subtle","payoff evidence exists","release feels arbitrary"),
 _arc("suppression_to_explosion","Suppression To Explosion",["suppression","pressure","explosion","aftershock"],"strong","source supports contrast in intensity","manufactured climax"),
 _arc("admiration_to_vulnerability","Admiration To Vulnerability",["radiance","fracture","vulnerability","renewed regard"],"strong","both public image and vulnerable evidence exist","exploitative framing"),
 _arc("worship_distance_reframe","Worship Distance Reframe",["idolization","distance","contradiction","reinterpretation"],"extreme","contradictory evidence is contextualized","false takedown"),
 _arc("joy_to_silence","Joy To Silence",["joy","acceleration","rupture","silence"],"extreme","a real turn supports the silence","cheap shock"),
 _arc("fall_and_return","Fall And Return",["promise","failure","effort","return"],"strong","failure and recovery are evidenced","fabricated inspiration"),
 _arc("cyclical_memory","Cyclical Memory",["present","memory","variation","return"],"subtle","motif/temporal evidence recurs","confusing chronology"),
 _arc("unresolved_aftertaste","Unresolved Aftertaste",["question","fragments","near-answer","open end"],"subtle","non-closure serves theme","incomplete edit"),
 _arc("comic_misdirection","Comic Misdirection",["setup","false expectation","reveal","deadpan hold"],"strong","timing and context support humor","mockery or confusion"),
]

def build_style_template_package(project_path: Path):
 project_path=project_path.resolve(); config=load_project_config(project_path); root=project_root(project_path); state=load_state(root)
 if state is None: raise StyleTemplatesError("style-templates requires init first")
 data=root/WORKSPACE_DIR/DATA_DIR; sources_path=data/"sources.jsonl"
 if not sources_path.exists(): raise StyleTemplatesError("style-templates requires current source scan")
 sources=[SourceRecord.model_validate_json(x) for x in sources_path.read_text().splitlines() if x.strip()]
 if not sources: raise StyleTemplatesError("style-templates requires at least one source")
 strategy_path=data/"creative_strategy_package.json"; source_types={str(x.source_type.value) for x in sources if x.source_type.value}; confirmed={str(x.source_type.value) for x in sources if x.source_type.user_confirmed or x.source_type.method=="sources_csv"}; brief=" ".join([config.project.title,config.creative_brief.theme,*config.creative_brief.tone]).lower()
 compatibility=[_compatibility(x,source_types,confirmed,brief,config) for x in CONTENT_TEMPLATES]; best_score=max(x.compatibility_score for x in compatibility); best=[x.template_id for x in compatibility if abs(x.compatibility_score-best_score)<.0001]
 examples=_examples(best[0]); warnings=["content-form compatibility is advisory; no content form, aesthetic style, or combination was selected or applied","aesthetic styles are an open creative vocabulary, not semantic claims or hard limits"]
 if not confirmed: warnings.append("source types are not confirmed; creative-brief signals lower compatibility confidence")
 if not strategy_path.exists(): warnings.append("creative strategy package is unavailable; combinations are illustrative only")
 key=fingerprint_file(project_path)+fingerprint_file(sources_path)+(fingerprint_file(strategy_path) if strategy_path.exists() else "none")
 package=StyleTemplatePackage(package_id="style_space_"+hashlib.sha256(key.encode()).hexdigest()[:20],project_id=config.project.id,project_ref=project_path.relative_to(root).as_posix(),project_fingerprint=fingerprint_file(project_path),sources_ref=sources_path.relative_to(root).as_posix(),sources_fingerprint=fingerprint_file(sources_path),creative_strategy_ref=strategy_path.relative_to(root).as_posix() if strategy_path.exists() else None,creative_strategy_fingerprint=fingerprint_file(strategy_path) if strategy_path.exists() else None,content_templates=CONTENT_TEMPLATES,aesthetic_styles=AESTHETIC_STYLES,creative_techniques=CREATIVE_TECHNIQUES,emotional_arcs=EMOTIONAL_ARCS,content_compatibility=compatibility,best_match_content_template_ids=best,combination_examples=examples,source_type_evidence_status="confirmed" if confirmed else "partial",status="degraded",warnings=warnings)
 canonical=data/"style_template_package.json"; report=root/config.paths.output_dir/"style_template_package.md"; atomic_write_text(canonical,package.model_dump_json(indent=2)+"\n"); atomic_write_text(report,_report(package)); run_id=new_run_id(); refs=[canonical.relative_to(root).as_posix(),report.relative_to(root).as_posix()]; inputs=[("project",project_path),("sources",sources_path)]+([("strategies",strategy_path)] if strategy_path.exists() else []); state.steps["style_templates"]=StepLedgerEntry(status=StepStatus.completed_with_warnings,input_fingerprint=fingerprint_inputs(inputs),output_refs=refs,last_run_id=run_id,warnings=warnings); state.active_mode=ActiveMode.creative; state.overall_status=OverallStatus.degraded; state.latest_run_id=run_id; state.updated_at=utc_now(); runs=root/WORKSPACE_DIR/RUNS_DIR/run_id; runs.mkdir(parents=True,exist_ok=True); write_json(runs/"command.json",{"command":"style-templates","project":str(project_path)}); write_json(runs/"environment.json",environment_snapshot()); write_json(runs/"step_result.json",{"step":"style_templates","content_template_count":len(CONTENT_TEMPLATES),"aesthetic_style_count":len(AESTHETIC_STYLES),"technique_count":len(CREATIVE_TECHNIQUES),"emotional_arc_count":len(EMOTIONAL_ARCS),"selected_combination_id":None,"template_applied":False,"output_refs":refs}); save_state(root,state); write_run_report(root/config.paths.output_dir,state,warnings); return canonical,report,package,warnings

def _compatibility(t,source_types,confirmed,brief,config):
 direct=sorted((source_types-{"other"}).intersection(t.intended_source_types)); confirmed_direct=sorted((confirmed-{"other"}).intersection(t.intended_source_types)); hits=[x for x in t.brief_keywords if x.lower() in brief]; score=.12; confidence=.22; matched=[]; conflicts=[]; missing=[]
 if confirmed_direct: score+=.55; confidence+=.5; matched.append("confirmed source: "+", ".join(confirmed_direct))
 elif direct: score+=.32; confidence+=.2; matched.append("unconfirmed source: "+", ".join(direct))
 if hits: score+=.24; confidence+=.12; matched.append("brief signals: "+", ".join(hits))
 if config.creative_brief.platform in t.intended_platforms: score+=.06
 if config.creative_brief.aspect_ratio in t.intended_aspects: score+=.03
 if any("transcript" in x for x in t.required_evidence) and config.features.transcription.value=="off": missing.append("transcript/manual semantic notes")
 score=round(min(1,score),4); confidence=round(min(1,confidence),4); status="compatible" if score>=.7 and not missing else "conditional" if score>=.35 else "incompatible"
 return TemplateCompatibility(template_id=t.template_id,compatibility_score=score,confidence=confidence,status=status,matched_signals=matched,conflicts=conflicts,missing_evidence=missing,application_constraints=["explicit user selection required","style/technique/arc remain separately selectable","break mode requires form, feeling, meaning, risk, playback verification, and fallback"])

def _examples(content_id):
 data=[("idol_highlight","idol_gloss","portrait_highlight",["motif_repetition"],"linear_rise",{"structure":"follow","rhythm":"bend","sound":"follow"},"Radiant subject-forward highlight with recurring visual motif"),("hot_blooded_reversal","hot_blooded","high_energy",["delayed_payoff","extreme_reversal"],"suppression_to_explosion",{"structure":"bend","rhythm":"break","sound":"break"},"Suppress expected climax, then reverse image/sound/rhythm together"),("inspirational_process","inspirational","narrative_clarity",["contrast_montage","long_take_breathing"],"fall_and_return",{"structure":"follow","rhythm":"bend","sound":"follow"},"Let effort and failure earn the final rise"),("restrained_aftertaste","restrained_premium","emotional_arc",["intentional_silence","long_take_breathing"],"unresolved_aftertaste",{"structure":"bend","rhythm":"break","sound":"bend"},"Use negative space and deliberate non-closure"),("cinematic_cross_media","cinematic","narrative_clarity",["nonlinear_reorder","sound_image_dislocation"],"cyclical_memory",{"structure":"break","rhythm":"bend","sound":"break"},"Connect media periods through motif and sound bridges"),("experimental_extreme","experimental_contrast","emotional_arc",["intentional_rupture","extreme_reversal"],"worship_distance_reframe",{"structure":"break","rhythm":"break","sound":"break"},"Build one reading, fracture it, and reframe the person with contextual evidence")]
 return [CreativeCombinationExample(combination_id=i,content_template_id=content_id,aesthetic_style_id=s,creative_strategy_id=strategy,technique_ids=tech,emotional_arc_id=arc,rule_modes=modes,concept=concept,intended_effect="a deliberate, reviewable creative transformation",meaning="must be justified by current person/theme evidence",risks=["semantic overclaim","style overwhelms subject","reversal becomes gimmick"]) for i,s,strategy,tech,arc,modes,concept in data]

def _report(p):
 lines=["# Open Style Grammar","",f"- Package: `{p.package_id}`",f"- Content forms: `{len(p.content_templates)}`",f"- Aesthetic styles: `{len(p.aesthetic_styles)}`",f"- Creative techniques: `{len(p.creative_techniques)}`",f"- Emotional arcs: `{len(p.emotional_arcs)}`",f"- Best content matches: `{', '.join(p.best_match_content_template_ids)}`","- Rule modes: `follow / bend / break`","- Extreme reversal: `supported`","- Selection/application: `none`","","## Aesthetic Styles",""]+[f"- `{x.style_id}`: {x.name}" for x in p.aesthetic_styles]+["","## Combination Examples",""]+[f"- `{x.combination_id}`: {x.concept}" for x in p.combination_examples]+["","## Warnings",""]+[f"- {x}" for x in p.warnings]; return "\n".join(lines)+"\n"
